apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-docker-wprz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-docker-wprz
    app.kubernetes.io/part-of: ec-boot-docker
  name: java-springboot-hello-docker-wprz
  namespace: bsutter-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: java-springboot-hello-docker-wprz
status:
  loadBalancer: {}
